[general]
	# Toggle the dynamic combat music feature on or off.
	# default: false
	enabled = false
	# The minimum amount of hostile mobs that must be nearby to trigger combat music.
	# default: 3
	minPursuitEntities = 3
	# How long combat music will continue playing after no hostile mobs are nearby.
	# default: 3
	decayTime = 3
	# List of SoundEvent Resource Locations that can be chosen for combat music.
	sounds = ["minecraft:music_disc.mellohi", "minecraft:music_disc.pigstep"]
	# Fades out background music when near a playing Jukebox.
	# default: true
	betterJukeboxes = true
	# The radius in blocks around a jukebox that will fade out background music.
	# default: 64.0
	jukeboxDistance = 64.0
