[modName]
	# Name: Formato del nombre del mod
	# Description: Cómo debe formatearse el nombre del mod en la información sobre herramientas para la interfaz JEI. Dejar en blanco para deshabilitar.
	# Valid Values: A chat formatting string.
	# Use these formatting colors:
	# BLACK DARK_BLUE DARK_GREEN DARK_AQUA DARK_RED DARK_PURPLE GOLD GRAY DARK_GRAY BLUE GREEN AQUA RED LIGHT_PURPLE YELLOW WHITE
	# With these formatting options:
	# OBFUSCATED BOLD STRIKETHROUGH UNDERLINE ITALIC
	# Default Value: BLUE ITALIC
	modNameFormat = 


