enablePinning = true
keepCentered = false
showModName = false
hideReiJeiOverlay = false
showAllRecipesInSurvival = true
partialCraftingEnabled = true
partialMarkingEnabled = true
settingsButton = true
enableBook = true

[rbip]
enableRecipeBookIsPain = true
enableTabPage = true

[newRecipes]
unlockAll = true
enableBounce = false

[instantCraft]
showButton = true
enabled = false

[alternativeRecipes]
onHover = true
noGrouped = false

[scrolling]
enableScrolling = true
scrollAround = false
