#Move the experience level display above the experience bar.
#Default Value: true
#Requires Restart: Game
move_experience_above_bar = true
#Defines a set of gui layers that should be shifted together with the hotbar.
#Default Value: [hotbarslotcycling:cycling_slots, enchantmentswitch:slot_overlay, lockedinslots:slot_overlay]
#Requires Restart: Game
hotbar_gui_layers = ["hotbarslotcycling:cycling_slots", "enchantmentswitch:slot_overlay", "lockedinslots:slot_overlay"]
#Height offset for the hotbar from the screen bottom.
# Default: 2
# Range: > 0
hotbar_offset = 2
