glowEnabled = true
beamEnabled = true
maxRenderDistance = 24

[common]
enabled = false
beamEnabled = false
rgb = "255,255,255"

[uncommon]
enabled = true
beamEnabled = true
rgb = "255,255,85"

[rare]
enabled = true
beamEnabled = true
rgb = "85,255,255"

[epic]
enabled = true
beamEnabled = true
rgb = "255,85,255"

[beam]
patternEnabled = true
beamHeight = 1.5
beamOffset = 0.3
beamWidth = 5
